receivers:
  otlp:
    protocols:
      grpc: # on port 4317
      http: # on port 4318

processors:
  batch:

exporters:
  otlp/traces:
    endpoint: "api.honeycomb.io:443"
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}

extensions:
  health_check:
    endpoint: :13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]